import type { Metadata } from "next";
import localFont from "next/font/local";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { AnimatePresence } from "framer-motion";
import "./globals.css";
import { Boxes } from "lucide-react";
import { BoxesCore } from "@/components/ui/background-boxes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BoxesCore/>
        <div className="grid grid-cols-12 gap-6 px-5 my-14 lg:mb-0 md:mb-16 sm:px-20 md:px-32 lg:px-36 xl:px-48 ">
          {/* // do this div style later (after putting the content) */}
          <div className="h-full col-span-12 p-4 text-base text-center bg-white lg:col-span-3 rounded-2xl dark:bg-black-500 shadow-custom-light dark:shadow-custom-dark">
            {/* //!sidebar */}
            <Sidebar />
          </div>
          <div className="flex flex-col col-span-12 overflow-hidden bg-blue-500 rounded-2xl dark:bg-black-500 dark:text-white lg:col-span-9 shadow-custom-light dark:shadow-custom-dark">
            {/* //!navbar */}
            <Navbar />
            {/* //!about */}
            <AnimatePresence>
              {children}
            </AnimatePresence>
          </div>
        </div>
      </body>
    </html>
  );
}
