
import type { Metadata } from "next";
import localFont from "next/font/local";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { AnimatePresence } from "framer-motion";
import "./globals.css";
import { motion } from "framer-motion";
import { BoxesCore } from "@/components/ui/background-boxes";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Sobhit Sinha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-black`}
        style={{fontFamily:'Inter'}}
      >
        <div className="h-full relative w-full overflow-hidden bg-black flex flex-col items-center justify-center rounded-lg">
          <BoxesCore />

          <div className="grid z-10 grid-cols-12 gap-6 px-5 my-14 lg:mb-0 md:mb-16 sm:px-20 md:px-32 lg:px-10 xl:px-12">
            {/* Sidebar - Keep size increased */}
            <div className="h-full col-span-12 p-4 text-base text-center bg-[#0e100f] lg:col-span-4 xl:col-span-3 rounded-2xl dark:bg-black-500 shadow-custom-light dark:shadow-custom-dark">
              {/* //!sidebar */}
              <Sidebar />
            </div>

            {/* Main content - Expand to almost touch the right side of the screen */}
            <div className="flex flex-col col-span-12 overflow-hidden bg-[#0e100f]/85 rounded-2xl dark:bg-black-500 dark:text-white lg:col-span-8 xl:col-span-9 shadow-custom-light text-white dark:shadow-custom-dark lg:mr-0 xl:mr-0">
              {/* //!navbar */}
              <Navbar />
              {/* //!about */}
              <AnimatePresence>
                {children}
              </AnimatePresence>
            </div>
          </div>




        </div>

      </body>
    </html>
  );
}
